# Configuración del sitio

title: Calzados Arrieta
phone: +34 948 24 30 63
email: calzadosarrieta@gmail.com
address: C. Paulino Caballero 12, 31003 Pamplona

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://calzadosarrieta.github.io/web" # the base hostname & protocol for your site, e.g. http://example.com
keywords: calzados alpargatas zapatillas
author: Calzados Arrieta

locale: es_ES
street: C. Paulino Caballero 12
city: Pamplona
region: Navarra
zip: 31003
country: Spain
latitude: 42.81222518996606
longitude: -1.64002290369713

logo:
sameAs:
  facebook: https://www.facebook.com/p/Calzados-Arrieta-100063896959347
  google_maps: https://maps.app.goo.gl/1w5eFcZWMwopUFA16

webmaster_verifications:
  google: 1234

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/alpargatas.png
      type: Product


# Build settings (NO TOCAR)
theme: minima
plugins:
  - jekyll-seo-tag
