# Configuración del sitio

title: Calzados Arrieta
description: Calzados Arrieta, la mejor tienda de zapatillas y alpargatas en Pamplona...
author: Calzados Arrieta

phone: 948 24 30 63
email: calzadosarrieta@gmail.com
address: C. Paulino Caballero 12, 31003 Pamplona

locale: es_ES
street: C. Paulino Caballero 12
city: Pamplona
region: Navarra
zip: 31003
country: Spain
latitude: 42.81222518996606
longitude: -1.64002290369713
icon: img/favicon.ico


logo:
sameAs:
  facebook: https://www.facebook.com/p/Calzados-Arrieta-100063896959347
  google_maps: https://maps.app.goo.gl/1w5eFcZWMwopUFA16

webmaster_verifications:
  google: 1234

defaults:
  - scope:
      path: ""
    values:
      image: img/alpargatas.png
      keywords: calzados alpargatas zapatillas


baseurl: "/web" # the subpath of your site, e.g. /blog
url: "https://calzadosarrieta.github.io" # the base hostname & protocol for your site, e.g. http://example.com






# Build settings (NO TOCAR)
theme: minima
plugins:
  - jekyll-seo-tag
